

// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).
// This file must remain in place relative to the generated scripts (<WebProject>/Scripts/Generated).


/// <reference path="coalesce.dependencies.d.ts" />
/// <reference path="Generated/Ko.ApplicationUser.g.ts" />
/// <reference path="Generated/Ko.ApplicationUserList.g.ts" />
/// <reference path="Generated/Ko.Child.g.ts" />
/// <reference path="Generated/Ko.ChildList.g.ts" />
/// <reference path="Generated/Ko.Thing.g.ts" />
/// <reference path="Generated/Ko.ThingList.g.ts" />
